### ISSUE TITLE
PeerWeb project should use Continuous Integration

### ISSUE THREAD

**Issue by tumland** [retrohacker/peerweb2.0#22] opened 2016-07-23 13:39 UTC
Something like travis-CI would help. 

The CI system would automatically run the tests, and build electron packages for all platforms.

**Comment by retrohacker** [comment] 2016-07-23 15:37
This will be part of #7

**Comment by retrohacker** [comment] 2016-07-25 19:27
Dropping this here. I'm going to try to use TravisCI for our CI/CD. Hold onto your butts.

**Comment by retrohacker** [comment] 2016-10-23 22:41
Current status of this:

TravisCI _does_ work for this. I've successfully tested and built binaries there. The problem is we need to do osx code signing, which requires we build on mac. From my understanding on TravisCI, that means we need to build all of the binaries on osx when the tests pass, which requires wine for cross compiling. Wine can be installed via brew, but takes forever and causes the build to timeout.

Looking for other solutions now, including plugging a macbook into my router and doing CI/CD from there.

**Comment by retrohacker** [comment] 2016-10-24 14:46
Closing this in favor of #7

**Closed as completed by retrohacker** 2016-10-24 14:46 UTC
